name: HelloWorld
on: [push]

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: "First Command"
        run: echo "Pawel"
      - run: echo "The name of this branch is ${{ github.ref }}"
      - name: "show structure"
        run: tree ./
      - run: echo "it works"
      
    
